export const capitalCities = [
  { name: "Adelaide", state: "SA", country: "AU" },
  { name: "Brisbane", state: "QLD", country: "AU" },
  { name: "Canberra", state: "ACT", country: "AU" },
  { name: "Darwin", state: "NT", country: "AU" },
  { name: "Melbourne", state: "VIC", country: "AU" },
  { name: "Hobart", state: "TAS", country: "AU" },
  { name: "Perth", state: "WA", country: "AU" },
  { name: "Sydney", state: "NSW", country: "AU" },
];

export const allCities = [
  { name: "Sydney", state: "NSW", country: "AU" },
  { name: "Melbourne", state: "VIC", country: "AU" },
  { name: "Brisbane", state: "QLD", country: "AU" },
  { name: "Perth", state: "WA", country: "AU" },
  { name: "Adelaide", state: "SA", country: "AU" },
  { name: "Gold Coast", state: "QLD", country: "AU" },
  { name: "Cranbourne", state: "VIC", country: "AU" },
  { name: "Canberra", state: "ACT", country: "AU" },
  { name: "Newcastle", state: "NSW", country: "AU" },
  { name: "Wollongong", state: "NSW", country: "AU" },
  { name: "Geelong", state: "VIC", country: "AU" },
  { name: "Hobart", state: "TAS", country: "AU" },
  { name: "Townsville", state: "QLD", country: "AU" },
  { name: "Ipswich", state: "QLD", country: "AU" },
  { name: "Cairns", state: "QLD", country: "AU" },
  { name: "Toowoomba", state: "QLD", country: "AU" },
  { name: "Darwin", state: "NT", country: "AU" },
  { name: "Ballarat", state: "VIC", country: "AU" },
  { name: "Bendigo", state: "VIC", country: "AU" },
  { name: "Launceston", state: "TAS", country: "AU" },
  { name: "Mackay", state: "QLD", country: "AU" },
  { name: "Rockhampton", state: "QLD", country: "AU" },
  { name: "Maitland", state: "NSW", country: "AU" },
  { name: "Bunbury", state: "WA", country: "AU" },
  { name: "Coffs Harbour", state: "NSW", country: "AU" },
  { name: "Bundaberg", state: "QLD", country: "AU" },
  { name: "Wagga Wagga", state: "NSW", country: "AU" },
  { name: "Hervey Bay", state: "QLD", country: "AU" },
  { name: "Shepparton", state: "VIC", country: "AU" },
  { name: "Albury", state: "NSW", country: "AU" },
  { name: "Port Macquarie", state: "NSW", country: "AU" },
  { name: "Pakenham", state: "VIC", country: "AU" },
  { name: "Tamworth", state: "NSW", country: "AU" },
  { name: "Caloundra", state: "QLD", country: "AU" },
  { name: "Orange", state: "NSW", country: "AU" },
  { name: "Dubbo", state: "NSW", country: "AU" },
  { name: "Geraldton", state: "WA", country: "AU" },
  { name: "Nowra", state: "NSW", country: "AU" },
  { name: "Bathurst", state: "NSW", country: "AU" },
  { name: "Queanbeyan", state: "NSW", country: "AU" },
  { name: "Frankston", state: "VIC", country: "AU" },
  { name: "Sunbury", state: "VIC", country: "AU" },
  { name: "Warrnambool", state: "VIC", country: "AU" },
  { name: "Wodonga", state: "VIC", country: "AU" },
  { name: "Albany", state: "WA", country: "AU" },
  { name: "Gladstone", state: "QLD", country: "AU" },
  { name: "Mildura", state: "VIC", country: "AU" },
  { name: "Southport", state: "QLD", country: "AU" },
  { name: "Alice Springs", state: "NT", country: "AU" },
  { name: "Dandenong", state: "VIC", country: "AU" },
  { name: "Kalgoorlie", state: "WA", country: "AU" },
  { name: "Mount Gambier", state: "SA", country: "AU" },
  { name: "Lismore", state: "NSW", country: "AU" },
  { name: "Maryborough", state: "QLD", country: "AU" },
  { name: "Quakers Hill", state: "NSW", country: "AU" },
  { name: "Gawler", state: "SA", country: "AU" },
  { name: "Caboolture", state: "QLD", country: "AU" },
  { name: "Ballina", state: "NSW", country: "AU" },
  { name: "Taree", state: "NSW", country: "AU" },
  { name: "Traralgon", state: "VIC", country: "AU" },
  { name: "Busselton", state: "WA", country: "AU" },
  { name: "Armidale", state: "NSW", country: "AU" },
  { name: "Goulburn", state: "NSW", country: "AU" },
  { name: "Devonport", state: "TAS", country: "AU" },
  { name: "Bacchus Marsh", state: "VIC", country: "AU" },
  { name: "Whyalla", state: "SA", country: "AU" },
  { name: "Cessnock", state: "NSW", country: "AU" },
  { name: "Gympie", state: "QLD", country: "AU" },
  { name: "Griffith", state: "NSW", country: "AU" },
  { name: "Kwinana", state: "WA", country: "AU" },
  { name: "Burnie", state: "TAS", country: "AU" },
  { name: "Wangaratta", state: "VIC", country: "AU" },
  { name: "Grafton", state: "NSW", country: "AU" },
  { name: "Yeppoon", state: "QLD", country: "AU" },
  { name: "Murray Bridge", state: "SA", country: "AU" },
  { name: "Mount Isa", state: "QLD", country: "AU" },
  { name: "Narangba", state: "QLD", country: "AU" },
  { name: "Mount Eliza", state: "VIC", country: "AU" },
  { name: "Broken Hill", state: "NSW", country: "AU" },
  { name: "Nerang", state: "QLD", country: "AU" },
  { name: "Karratha", state: "WA", country: "AU" },
  { name: "Mount Barker", state: "SA", country: "AU" },
  { name: "Horsham", state: "VIC", country: "AU" },
  { name: "Lara", state: "VIC", country: "AU" },
  { name: "Singleton", state: "NSW", country: "AU" },
  { name: "Port Lincoln", state: "SA", country: "AU" },
  { name: "Banora Point", state: "NSW", country: "AU" },
  { name: "Warwick", state: "QLD", country: "AU" },
  { name: "Rochedale", state: "QLD", country: "AU" },
  { name: "Kempsey", state: "NSW", country: "AU" },
  { name: "Ulladulla", state: "NSW", country: "AU" },
  { name: "Sale", state: "VIC", country: "AU" },
  { name: "Echuca", state: "VIC", country: "AU" },
  { name: "Australind", state: "WA", country: "AU" },
  { name: "Broome", state: "WA", country: "AU" },
  { name: "Port Hedland", state: "WA", country: "AU" },
  { name: "Warragul", state: "VIC", country: "AU" },
  { name: "Port Pirie", state: "SA", country: "AU" },
  { name: "Barwon Heads", state: "VIC", country: "AU" },
  { name: "Emerald", state: "QLD", country: "AU" },
  { name: "Ulverstone", state: "TAS", country: "AU" },
  { name: "Morwell", state: "VIC", country: "AU" },
  { name: "Gisborne", state: "VIC", country: "AU" },
  { name: "Port Augusta", state: "SA", country: "AU" },
  { name: "Forster", state: "NSW", country: "AU" },
  { name: "Penrith", state: "NSW", country: "AU" },
  { name: "Torquay", state: "VIC", country: "AU" },
  { name: "Jimboomba", state: "QLD", country: "AU" },
  { name: "Lithgow", state: "NSW", country: "AU" },
  { name: "Bowral", state: "NSW", country: "AU" },
  { name: "Goonellabah", state: "NSW", country: "AU" },
  { name: "Raymond Terrace", state: "NSW", country: "AU" },
  { name: "Leopold", state: "VIC", country: "AU" },
  { name: "Dalby", state: "QLD", country: "AU" },
  { name: "Campbelltown", state: "NSW", country: "AU" },
  { name: "Colac", state: "VIC", country: "AU" },
  { name: "Muswellbrook", state: "NSW", country: "AU" },
  { name: "Esperance", state: "WA", country: "AU" },
  { name: "Drouin", state: "VIC", country: "AU" },
  { name: "Rutherford", state: "NSW", country: "AU" },
  { name: "Nelson Bay", state: "NSW", country: "AU" },
  { name: "Inverell", state: "NSW", country: "AU" },
  { name: "Parkes", state: "NSW", country: "AU" },
  { name: "Somerville", state: "VIC", country: "AU" },
  { name: "Gracemere", state: "QLD", country: "AU" },
  { name: "Batemans Bay", state: "NSW", country: "AU" },
  { name: "Nambour", state: "QLD", country: "AU" },
  { name: "Swan Hill", state: "VIC", country: "AU" },
  { name: "Mareeba", state: "QLD", country: "AU" },
  { name: "Corinda", state: "QLD", country: "AU" },
  { name: "Samford", state: "QLD", country: "AU" },
  { name: "Mudgee", state: "NSW", country: "AU" },
  { name: "Casino", state: "NSW", country: "AU" },
  { name: "Portland", state: "VIC", country: "AU" },
  { name: "Kingston", state: "TAS", country: "AU" },
  { name: "Kingaroy", state: "QLD", country: "AU" },
  { name: "Kangaroo Flat", state: "VIC", country: "AU" },
  { name: "Bowen", state: "QLD", country: "AU" },
  { name: "Young", state: "NSW", country: "AU" },
  { name: "Cowra", state: "NSW", country: "AU" },
  { name: "Hamilton", state: "VIC", country: "AU" },
  { name: "Gunnedah", state: "NSW", country: "AU" },
  { name: "Mount Evelyn", state: "VIC", country: "AU" },
  { name: "Andergrove", state: "QLD", country: "AU" },
  { name: "Moree", state: "NSW", country: "AU" },
  { name: "Benalla", state: "VIC", country: "AU" },
  { name: "Currumbin", state: "QLD", country: "AU" },
  { name: "Wollert", state: "VIC", country: "AU" },
  { name: "Mittagong", state: "NSW", country: "AU" },
  { name: "Kelso", state: "NSW", country: "AU" },
  { name: "Yanchep", state: "WA", country: "AU" },
  { name: "Bentley", state: "WA", country: "AU" },
  { name: "Moe", state: "VIC", country: "AU" },
  { name: "Ayr", state: "QLD", country: "AU" },
  { name: "Moranbah", state: "QLD", country: "AU" },
  { name: "Leeton", state: "NSW", country: "AU" },
  { name: "Moss Vale", state: "NSW", country: "AU" },
  { name: "Wallan", state: "VIC", country: "AU" },
  { name: "Springwood", state: "NSW", country: "AU" },
  { name: "Lesmurdie", state: "WA", country: "AU" },
  { name: "Forbes", state: "NSW", country: "AU" },
  { name: "Emu Plains", state: "NSW", country: "AU" },
  { name: "Rye", state: "VIC", country: "AU" },
  { name: "Darley", state: "VIC", country: "AU" },
  { name: "Ararat", state: "VIC", country: "AU" },
  { name: "Tweed Heads", state: "NSW", country: "AU" },
  { name: "Highfields", state: "QLD", country: "AU" },
  { name: "Charters Towers", state: "QLD", country: "AU" },
  { name: "Melton", state: "VIC", country: "AU" },
  { name: "Katoomba", state: "NSW", country: "AU" },
  { name: "Kilmore", state: "VIC", country: "AU" },
  { name: "Mooroopna", state: "VIC", country: "AU" },
  { name: "Yarrawonga", state: "VIC", country: "AU" },
  { name: "Maryborough", state: "VIC", country: "AU" },
  { name: "Deniliquin", state: "NSW", country: "AU" },
  { name: "Mandurah", state: "WA", country: "AU" },
  { name: "Bli Bli", state: "QLD", country: "AU" },
  { name: "Kiama", state: "NSW", country: "AU" },
  { name: "Narre Warren North", state: "VIC", country: "AU" },
  { name: "Narrabri", state: "NSW", country: "AU" },
  { name: "Bairnsdale", state: "VIC", country: "AU" },
  { name: "Clifton Springs", state: "VIC", country: "AU" },
  { name: "North Tamborine", state: "QLD", country: "AU" },
  { name: "Bargara", state: "QLD", country: "AU" },
  { name: "Kingscliff", state: "NSW", country: "AU" },
  { name: "Healesville", state: "VIC", country: "AU" },
  { name: "Fremantle", state: "WA", country: "AU" },
  { name: "Blaxland", state: "NSW", country: "AU" },
  { name: "Atherton", state: "QLD", country: "AU" },
  { name: "Kyabram", state: "VIC", country: "AU" },
  { name: "Innisfail", state: "QLD", country: "AU" },
  { name: "Sanctuary Point", state: "NSW", country: "AU" },
  { name: "Collie", state: "WA", country: "AU" },
  { name: "Gatton", state: "QLD", country: "AU" },
  { name: "Merrimac", state: "NSW", country: "AU" },
  { name: "Murwillumbah", state: "NSW", country: "AU" },
  { name: "Urraween", state: "QLD", country: "AU" },
  { name: "Kyneton", state: "VIC", country: "AU" },
  { name: "Bongaree", state: "QLD", country: "AU" },
  { name: "Roma", state: "QLD", country: "AU" },
  { name: "Mount Cotton", state: "QLD", country: "AU" },
  { name: "Cootamundra", state: "NSW", country: "AU" },
  { name: "Beerwah", state: "QLD", country: "AU" },
  { name: "Castlemaine", state: "VIC", country: "AU" },
  { name: "Pottsville", state: "NSW", country: "AU" },
  { name: "Cooma", state: "NSW", country: "AU" },
  { name: "Gordonvale", state: "QLD", country: "AU" },
  { name: "Lysterfield", state: "VIC", country: "AU" },
  { name: "Bomaderry", state: "NSW", country: "AU" },
  { name: "Chinchilla", state: "QLD", country: "AU" },
  { name: "Northam", state: "WA", country: "AU" },
  { name: "Yass", state: "NSW", country: "AU" },
  { name: "Strathalbyn", state: "SA", country: "AU" },
  { name: "Burpengary", state: "QLD", country: "AU" },
  { name: "Waterford", state: "QLD", country: "AU" },
  { name: "Lennox Head", state: "NSW", country: "AU" },
  { name: "Beaudesert", state: "QLD", country: "AU" },
  { name: "Margaret River", state: "WA", country: "AU" },
  { name: "Helensburgh", state: "NSW", country: "AU" },
  { name: "Goondiwindi", state: "QLD", country: "AU" },
  { name: "Seymour", state: "VIC", country: "AU" },
  { name: "Nambucca Heads", state: "NSW", country: "AU" },
  { name: "Nuriootpa", state: "SA", country: "AU" },
  { name: "Wauchope", state: "NSW", country: "AU" },
  { name: "Tumut", state: "NSW", country: "AU" },
  { name: "Tuncurry", state: "NSW", country: "AU" },
  { name: "Glen Innes", state: "NSW", country: "AU" },
  { name: "Yamba", state: "NSW", country: "AU" },
  { name: "Wentworth Falls", state: "NSW", country: "AU" },
  { name: "South Grafton", state: "NSW", country: "AU" },
  { name: "Kurri Kurri", state: "NSW", country: "AU" },
  { name: "Stawell", state: "VIC", country: "AU" },
  { name: "Cobram", state: "VIC", country: "AU" },
  { name: "Wynyard", state: "TAS", country: "AU" },
  { name: "Naracoorte", state: "SA", country: "AU" },
  { name: "North Mackay", state: "QLD", country: "AU" },
  { name: "Cannington", state: "WA", country: "AU" },
  { name: "Woodend", state: "VIC", country: "AU" },
  { name: "Dromana", state: "VIC", country: "AU" },
  { name: "Emerald", state: "VIC", country: "AU" },
  { name: "Biloela", state: "QLD", country: "AU" },
  { name: "Alstonville", state: "NSW", country: "AU" },
  { name: "Cannonvale", state: "QLD", country: "AU" },
  { name: "Point Vernon", state: "QLD", country: "AU" },
  { name: "Palmwoods", state: "QLD", country: "AU" },
  { name: "Scone", state: "NSW", country: "AU" },
  { name: "Whittlesea", state: "VIC", country: "AU" },
  { name: "East Ballina", state: "NSW", country: "AU" },
  { name: "Sarina", state: "QLD", country: "AU" },
  { name: "Byron Bay", state: "NSW", country: "AU" },
  { name: "Corowa", state: "NSW", country: "AU" },
  { name: "Richmond", state: "NSW", country: "AU" },
  { name: "Cooranbong", state: "NSW", country: "AU" },
  { name: "Bullsbrook", state: "WA", country: "AU" },
  { name: "Inverloch", state: "VIC", country: "AU" },
  { name: "New Norfolk", state: "TAS", country: "AU" },
  { name: "Stanthorpe", state: "QLD", country: "AU" },
  { name: "Wingham", state: "NSW", country: "AU" },
  { name: "Irymple", state: "VIC", country: "AU" },
  { name: "Dunsborough", state: "WA", country: "AU" },
  { name: "Kununurra", state: "WA", country: "AU" },
  { name: "Smithfield Heights", state: "QLD", country: "AU" },
  { name: "Woolgoolga", state: "NSW", country: "AU" },
  { name: "Bannockburn", state: "VIC", country: "AU" },
  { name: "Maffra", state: "VIC", country: "AU" },
  { name: "Tannum Sands", state: "QLD", country: "AU" },
  { name: "Ocean Shores", state: "NSW", country: "AU" },
  { name: "Howard Springs", state: "NT", country: "AU" },
  { name: "Leongatha", state: "VIC", country: "AU" },
  { name: "Worragee", state: "NSW", country: "AU" },
  { name: "Tahmoor", state: "NSW", country: "AU" },
  { name: "Red Cliffs", state: "VIC", country: "AU" },
  { name: "Glenbrook", state: "NSW", country: "AU" },
  { name: "McMinns Lagoon", state: "NT", country: "AU" },
  { name: "Kiama Downs", state: "NSW", country: "AU" },
  { name: "Hazelbrook", state: "NSW", country: "AU" },
  { name: "Wonthaggi", state: "VIC", country: "AU" },
  { name: "Junee", state: "NSW", country: "AU" },
  { name: "Pinjarra", state: "WA", country: "AU" },
  { name: "Encounter Bay", state: "SA", country: "AU" },
  { name: "Nairne", state: "SA", country: "AU" },
  { name: "Cowes", state: "VIC", country: "AU" },
  { name: "Boulder", state: "WA", country: "AU" },
  { name: "Picton", state: "NSW", country: "AU" },
  { name: "Salamander Bay", state: "NSW", country: "AU" },
  { name: "Lakes Entrance", state: "VIC", country: "AU" },
  { name: "Mansfield", state: "VIC", country: "AU" },
  { name: "Churchill", state: "VIC", country: "AU" },
  { name: "Bucasia", state: "QLD", country: "AU" },
  { name: "Boyne Island", state: "QLD", country: "AU" },
  { name: "Blackwater", state: "QLD", country: "AU" },
  { name: "Millicent", state: "SA", country: "AU" },
  { name: "Oakey", state: "QLD", country: "AU" },
  { name: "Temora", state: "NSW", country: "AU" },
  { name: "Narromine", state: "NSW", country: "AU" },
  { name: "Ningi", state: "QLD", country: "AU" },
  { name: "Bega", state: "NSW", country: "AU" },
  { name: "Mount Low", state: "QLD", country: "AU" },
  { name: "Leura", state: "NSW", country: "AU" },
  { name: "Renmark", state: "SA", country: "AU" },
  { name: "South West Rocks", state: "NSW", country: "AU" },
  { name: "Tanunda", state: "SA", country: "AU" },
  { name: "Kadina", state: "SA", country: "AU" },
  { name: "Newman", state: "WA", country: "AU" },
  { name: "Glenella", state: "QLD", country: "AU" },
  { name: "Roxby Downs", state: "SA", country: "AU" },
  { name: "Numurkah", state: "VIC", country: "AU" },
  { name: "Korumburra", state: "VIC", country: "AU" },
  { name: "Rasmussen", state: "QLD", country: "AU" },
  { name: "Tatura", state: "VIC", country: "AU" },
  { name: "Carnarvon", state: "WA", country: "AU" },
  { name: "Romsey", state: "VIC", country: "AU" },
  { name: "Blackheath", state: "NSW", country: "AU" },
  { name: "Bargo", state: "NSW", country: "AU" },
  { name: "Old Bar", state: "NSW", country: "AU" },
  { name: "Narrandera", state: "NSW", country: "AU" },
  { name: "Ingham", state: "QLD", country: "AU" },
  { name: "Manjimup", state: "WA", country: "AU" },
  { name: "George Town", state: "TAS", country: "AU" },
  { name: "Wyong", state: "NSW", country: "AU" },
  { name: "Broadford", state: "VIC", country: "AU" },
  { name: "Drysdale", state: "VIC", country: "AU" },
  { name: "Narrogin", state: "WA", country: "AU" },
  { name: "Cockatoo", state: "VIC", country: "AU" },
  { name: "Victor Harbor", state: "SA", country: "AU" },
  { name: "Moama", state: "NSW", country: "AU" },
  { name: "Bungendore", state: "NSW", country: "AU" },
  { name: "Latrobe", state: "TAS", country: "AU" },
  { name: "Beachmere", state: "QLD", country: "AU" },
  { name: "Berri", state: "SA", country: "AU" },
  { name: "Wellington", state: "NSW", country: "AU" },
  { name: "Tenterfield", state: "NSW", country: "AU" },
  { name: "Thirlmere", state: "NSW", country: "AU" },
  { name: "Legana", state: "TAS", country: "AU" },
  { name: "Faulconbridge", state: "NSW", country: "AU" },
  { name: "The Entrance", state: "NSW", country: "AU" },
  { name: "Cobar", state: "NSW", country: "AU" },
  { name: "Wallaroo", state: "SA", country: "AU" },
  { name: "Moruya", state: "NSW", country: "AU" },
  { name: "Gerringong", state: "NSW", country: "AU" },
  { name: "Sandstone Point", state: "QLD", country: "AU" },
  { name: "Tambourine", state: "QLD", country: "AU" },
  { name: "Margate", state: "TAS", country: "AU" },
  { name: "Trafalgar", state: "VIC", country: "AU" },
  { name: "Somerset", state: "TAS", country: "AU" },
  { name: "Marian", state: "QLD", country: "AU" },
  { name: "Weipa", state: "QLD", country: "AU" },
  { name: "Kerang", state: "VIC", country: "AU" },
  { name: "Westbrook", state: "QLD", country: "AU" },
  { name: "Smithton", state: "TAS", country: "AU" },
  { name: "Longford", state: "TAS", country: "AU" },
  { name: "Karana Downs", state: "QLD", country: "AU" },
  { name: "Beechworth", state: "VIC", country: "AU" },
  { name: "Penguin", state: "TAS", country: "AU" },
  { name: "Anna Bay", state: "NSW", country: "AU" },
  { name: "Loxton", state: "SA", country: "AU" },
  { name: "Pearcedale", state: "VIC", country: "AU" },
  { name: "Landsborough", state: "QLD", country: "AU" },
  { name: "Laidley", state: "QLD", country: "AU" },
  { name: "Wonga Park", state: "VIC", country: "AU" },
  { name: "Peregian Beach", state: "QLD", country: "AU" },
  { name: "Cooroy", state: "QLD", country: "AU" },
  { name: "Bellingen", state: "NSW", country: "AU" },
  { name: "Riddell", state: "VIC", country: "AU" },
  { name: "Suffolk Park", state: "NSW", country: "AU" },
  { name: "Buninyong", state: "VIC", country: "AU" },
  { name: "Weston", state: "NSW", country: "AU" },
  { name: "Katanning", state: "WA", country: "AU" },
  { name: "Bellbrae", state: "VIC", country: "AU" },
  { name: "Sawtell", state: "NSW", country: "AU" },
  { name: "Silverdale", state: "NSW", country: "AU" },
  { name: "Tallebudgera", state: "QLD", country: "AU" },
  { name: "Bay View", state: "NSW", country: "AU" },
  { name: "Portarlington", state: "VIC", country: "AU" },
  { name: "Nanango", state: "QLD", country: "AU" },
  { name: "Logan Village", state: "QLD", country: "AU" },
  { name: "Koo-Wee-Rup", state: "VIC", country: "AU" },
  { name: "Glass House Mountains", state: "QLD", country: "AU" },
  { name: "Sussex Inlet", state: "NSW", country: "AU" },
  { name: "Proserpine", state: "QLD", country: "AU" },
  { name: "Merimbula", state: "NSW", country: "AU" },
  { name: "Scarness", state: "QLD", country: "AU" },
  { name: "Port Douglas", state: "QLD", country: "AU" },
  { name: "Gosford", state: "NSW", country: "AU" },
  { name: "Bridgewater", state: "SA", country: "AU" },
  { name: "Lake Cathie", state: "NSW", country: "AU" },
  { name: "Condobolin", state: "NSW", country: "AU" },
  { name: "Paynesville", state: "VIC", country: "AU" },
  { name: "Woodford", state: "QLD", country: "AU" },
  { name: "Maddingley", state: "VIC", country: "AU" },
  { name: "Hurstbridge", state: "VIC", country: "AU" },
  { name: "Quirindi", state: "NSW", country: "AU" },
  { name: "Maleny", state: "QLD", country: "AU" },
  { name: "Calliope", state: "QLD", country: "AU" },
  { name: "North Beach", state: "WA", country: "AU" },
  { name: "Walkerston", state: "QLD", country: "AU" },
  { name: "Blayney", state: "NSW", country: "AU" },
  { name: "Camperdown", state: "VIC", country: "AU" },
  { name: "Aldgate", state: "SA", country: "AU" },
  { name: "Port Fairy", state: "VIC", country: "AU" },
  { name: "Tyabb", state: "VIC", country: "AU" },
  { name: "Lowood", state: "QLD", country: "AU" },
  { name: "Charleville", state: "QLD", country: "AU" },
  { name: "Derby", state: "WA", country: "AU" },
  { name: "Mooloolah", state: "QLD", country: "AU" },
  { name: "Pittsworth", state: "QLD", country: "AU" },
  { name: "Vincentia", state: "NSW", country: "AU" },
  { name: "Coonabarabran", state: "NSW", country: "AU" },
  { name: "Euroa", state: "VIC", country: "AU" },
  { name: "Oberon", state: "NSW", country: "AU" },
  { name: "Woombye", state: "QLD", country: "AU" },
  { name: "Nhulunbuy", state: "NT", country: "AU" },
  { name: "Camden", state: "NSW", country: "AU" },
  { name: "Murrumbateman", state: "NSW", country: "AU" },
  { name: "Fernvale", state: "QLD", country: "AU" },
  { name: "East Hills", state: "NSW", country: "AU" },
  { name: "Bohle Plains", state: "QLD", country: "AU" },
  { name: "Junortoun", state: "VIC", country: "AU" },
  { name: "Myrtleford", state: "VIC", country: "AU" },
  { name: "Crib Point", state: "VIC", country: "AU" },
  { name: "Marcoola", state: "QLD", country: "AU" },
  { name: "Mullumbimby", state: "NSW", country: "AU" },
  { name: "Creswick", state: "VIC", country: "AU" },
  { name: "Clare", state: "SA", country: "AU" },
  { name: "Tura Beach", state: "NSW", country: "AU" },
  { name: "Eden", state: "NSW", country: "AU" },
  { name: "West Wyalong", state: "NSW", country: "AU" },
  { name: "Gilgandra", state: "NSW", country: "AU" },
  { name: "Rochester", state: "VIC", country: "AU" },
  { name: "McLaren Vale", state: "SA", country: "AU" },
  { name: "Miners Rest", state: "VIC", country: "AU" },
  { name: "Robinvale", state: "VIC", country: "AU" },
  { name: "Wilton", state: "NSW", country: "AU" },
  { name: "Riverview", state: "QLD", country: "AU" },
  { name: "Bogangar", state: "NSW", country: "AU" },
  { name: "Shoalhaven Heads", state: "NSW", country: "AU" },
  { name: "Saint George", state: "QLD", country: "AU" },
  { name: "Little Hampton", state: "SA", country: "AU" },
  { name: "Clermont", state: "QLD", country: "AU" },
  { name: "Home Hill", state: "QLD", country: "AU" },
  { name: "Central Coast", state: "NSW", country: "AU" },
  { name: "Kuranda", state: "QLD", country: "AU" },
  { name: "Wilberforce", state: "NSW", country: "AU" },
  { name: "Tom Price", state: "WA", country: "AU" },
  { name: "Urunga", state: "NSW", country: "AU" },
  { name: "Dysart", state: "QLD", country: "AU" },
  { name: "Two Rocks", state: "WA", country: "AU" },
  { name: "Ballan", state: "VIC", country: "AU" },
  { name: "Gloucester", state: "NSW", country: "AU" },
  { name: "Bonny Hills", state: "NSW", country: "AU" },
  { name: "Longreach", state: "QLD", country: "AU" },
  { name: "Stirling", state: "SA", country: "AU" },
  { name: "Perth", state: "TAS", country: "AU" },
  { name: "Bordertown", state: "SA", country: "AU" },
  { name: "Lewiston", state: "SA", country: "AU" },
  { name: "Waroona", state: "WA", country: "AU" },
  { name: "Leschenault", state: "WA", country: "AU" },
  { name: "Terranora", state: "NSW", country: "AU" },
  { name: "Kapunda", state: "SA", country: "AU" },
  { name: "Woori Yallock", state: "VIC", country: "AU" },
  { name: "Saint Georges Basin", state: "NSW", country: "AU" },
  { name: "Pomona", state: "QLD", country: "AU" },
  { name: "Sorell", state: "TAS", country: "AU" },
  { name: "Tea Gardens", state: "NSW", country: "AU" },
  { name: "Culburra", state: "NSW", country: "AU" },
  { name: "Yarra Glen", state: "VIC", country: "AU" },
  { name: "Beaconsfield Upper", state: "VIC", country: "AU" },
  { name: "Morisset", state: "NSW", country: "AU" },
  { name: "Cohuna", state: "VIC", country: "AU" },
  { name: "Merredin", state: "WA", country: "AU" },
  { name: "Deloraine", state: "TAS", country: "AU" },
  { name: "Evans Head", state: "NSW", country: "AU" },
  { name: "Rosewood", state: "QLD", country: "AU" },
  { name: "Greta", state: "NSW", country: "AU" },
  { name: "Wollongbar", state: "NSW", country: "AU" },
  { name: "Donnybrook", state: "WA", country: "AU" },
  { name: "McCrae", state: "VIC", country: "AU" },
  { name: "Angle Vale", state: "SA", country: "AU" },
  { name: "Bridgetown", state: "WA", country: "AU" },
  { name: "North Wonthaggi", state: "VIC", country: "AU" },
  { name: "Heathcote", state: "VIC", country: "AU" },
  { name: "Howlong", state: "NSW", country: "AU" },
  { name: "Williamstown", state: "SA", country: "AU" },
  { name: "Harvey", state: "WA", country: "AU" },
  { name: "Coonamble", state: "NSW", country: "AU" },
  { name: "Uralla", state: "NSW", country: "AU" },
  { name: "Bundanoon", state: "NSW", country: "AU" },
  { name: "Cloncurry", state: "QLD", country: "AU" },
  { name: "Tolga", state: "QLD", country: "AU" },
  { name: "Huonville", state: "TAS", country: "AU" },
  { name: "Merbein", state: "VIC", country: "AU" },
  { name: "Alexandra", state: "VIC", country: "AU" },
  { name: "Waikerie", state: "SA", country: "AU" },
  { name: "Point Lonsdale", state: "VIC", country: "AU" },
  { name: "Hill Top", state: "NSW", country: "AU" },
  { name: "Stirling North", state: "SA", country: "AU" },
  { name: "Hahndorf", state: "SA", country: "AU" },
  { name: "Berry", state: "NSW", country: "AU" },
  { name: "Burnett Heads", state: "QLD", country: "AU" },
  { name: "Moore Park", state: "QLD", country: "AU" },
  { name: "Burradoo", state: "NSW", country: "AU" },
  { name: "Mannum", state: "SA", country: "AU" },
  { name: "Wooroloo", state: "WA", country: "AU" },
  { name: "Crookwell", state: "NSW", country: "AU" },
  { name: "Appin", state: "NSW", country: "AU" },
  { name: "Cooloola Cove", state: "QLD", country: "AU" },
  { name: "Cooktown", state: "QLD", country: "AU" },
  { name: "Jindabyne", state: "NSW", country: "AU" },
  { name: "Maclean", state: "NSW", country: "AU" },
  { name: "Stratford", state: "VIC", country: "AU" },
  { name: "Lawson", state: "NSW", country: "AU" },
  { name: "Thursday Island", state: "QLD", country: "AU" },
  { name: "Woodside", state: "SA", country: "AU" },
  { name: "Narooma", state: "NSW", country: "AU" },
  { name: "Macksville", state: "NSW", country: "AU" },
  { name: "Molong", state: "NSW", country: "AU" },
  { name: "Grenfell", state: "NSW", country: "AU" },
  { name: "Yarrabah Aboriginal Community", state: "QLD", country: "AU" },
  { name: "Denmark", state: "WA", country: "AU" },
  { name: "Bonville", state: "NSW", country: "AU" },
  { name: "Walcha", state: "NSW", country: "AU" },
  { name: "Manilla", state: "NSW", country: "AU" },
  { name: "Yarra Junction", state: "VIC", country: "AU" },
  { name: "Daylesford", state: "VIC", country: "AU" },
  { name: "York", state: "WA", country: "AU" },
  { name: "Anglesea", state: "VIC", country: "AU" },
  { name: "Kambalda", state: "WA", country: "AU" },
  { name: "Lobethal", state: "SA", country: "AU" },
  { name: "The Oaks", state: "NSW", country: "AU" },
  { name: "Gulgong", state: "NSW", country: "AU" },
  { name: "Finley", state: "NSW", country: "AU" },
  { name: "Capel", state: "WA", country: "AU" },
  { name: "Korora", state: "NSW", country: "AU" },
  { name: "Exmouth", state: "WA", country: "AU" },
  { name: "Boonah", state: "QLD", country: "AU" },
  { name: "Saint Leonards", state: "VIC", country: "AU" },
  { name: "Vasse", state: "WA", country: "AU" },
  { name: "Aberdare", state: "NSW", country: "AU" },
  { name: "Bunyip", state: "VIC", country: "AU" },
  { name: "Dodges Ferry", state: "TAS", country: "AU" },
  { name: "Lancefield", state: "VIC", country: "AU" },
  { name: "Palm Island", state: "QLD", country: "AU" },
  { name: "Currie", state: "TAS", country: "AU" },
];
